### ISSUE TITLE
"git help pw" does not work

### ISSUE THREAD

**Issue by tromey** [getpatchwork/git-pw#15]
I installed git-pw using pip.  I was hoping to read the manual using "git help pw", like I do for other git commands, but this did not work.

**Comment by stephenfin** [comment]
Yeah, installing man pages as part of a PyPI package is basically a lost cause as there's just way too much variation across different platforms to work. What could work is a package. I could spin these up if they were useful, at least for Fedora/RHEL (would need help with Ubuntu).

I'm going to close this as won't fix given that we can't fix these for packages.
