### ISSUE TITLE
git pw uses pager differently from the rest of git

### ISSUE THREAD

**Issue by tromey** [getpatchwork/git-pw#16]
`git help config` explains git's approach to choosing the pager and pager options.  However, `git pw` does not follow this same approach.  I was hoping that `git pw` would do what the rest of git did; the difference is pronounced enough in my case that I wind up invoking `git pw | cat` quite a bit.

**Comment by stephenfin** [comment]
@tromey Could you try #17 to see if this functions as expected. I think that enumerates the expected behavior pretty well.

**Comment by tromey** [comment]
Sorry it took me so long to get to this.  I tried it tonight and it did work like I expected.  Thank you very much!

**Comment by stephenfin** [comment]
Excellent. I'll merge this and release it early next week.
