### ISSUE TITLE
git-pw can't find patch by author's name

### ISSUE THREAD

**Issue by tromey** [getpatchwork/git-pw#18]
I'm not sure if this is a git-pw bug or a patchwork bug or a bug in our installation.  I filed it here since I observed it with git-pw, and because searching for the author's name in the patchwork web UI did find the patch.

If I ask for a patch by author, git-pw does not find it.  However, if I use the email address, the patch is found -- and it shows the author's name.

I have an example here, but since it is a real user I didn't feel comfortable posting their name and email address.  I could obfuscate it if that would be useful in any way.

**Comment by stephenfin** [comment]
Could you run the same command with `--debug`? This will show you the exact URLs the client is accessing and highlight any obvious issues. Feel free to share the output of the that log with some name/email details stripped, as necessary.

**Comment by tromey** [comment]
While doing that, of course I found something weird: this person spells their name two different ways, and I was using the wrong name according to git-pw.  However, in this case I don't understand git-pw's choice.

Also it occurs to me that the messages in question are archived publically, so I feel like it's fine to link to them now.

The patch in question is here: https://sourceware.org/ml/gdb-patches/2018-07/msg00629.html.  Here you can see that the sender is "Weimin Pan".  However, git pw says:

```
bapiya. git pw patch show 261 
+------------+----------------------------------------------------------------------+
| Property   | Value                                                                |
|------------+----------------------------------------------------------------------|
| ID         | 261                                                                  |
| Message ID | <1532128565-75923-1-git-send-email-weimin.pan@oracle.com>            |
| Date       | 2018-07-20T23:16:05                                                  |
| Name       | [PR,gdb/16841] virtual inheritance via typedef cannot find base      |
| URL        | https://patchwork.wildebeest.org/patch/261/                          |
| Submitter  | Wei-min Pan (weimin.pan@oracle.com)                                  |
| State      | new                                                                  |
| Archived   | False                                                                |
| Project    | gdb                                                                  |
| Delegate   |                                                                      |
| Commit Ref |                                                                      |
| Series     | 149  [PR,gdb/16841] virtual inheritance via typedef cannot find base |
+------------+----------------------------------------------------------------------+
```
That is, there is a hyphen in there now.  I double checked that the message-ids match.  This user does sometimes send email with a "-" in the first name.  So maybe patchwork decided that is the canonical name to use?

**Comment by stephenfin** [comment]
Sorry for the delay - I've been on PTO.

> The patch in question is here: sourceware.org/ml/gdb-patches/2018-07/msg00629.html. Here you can see that the sender is "Weimin Pan". However, git pw says:

This isn't anything to do with git-pw, really. That information is provided and controlled by Patchwork itself (i.e. the server). Recent versions of Patchwork included a change to ensure the name used in the latest email from a given submitter would be stored and used going forward (or until the next time the name changed). This was necessary as people's names change for the oddest of reasons. I would imagine this is what's happening here and, unfortunately, I can't think of an easy way to work around this. Perhaps you could rely on email addresses or a less specific name?

I'm going to close this as a non-issue, in light of the above. Please reopen if you have another suggestion for how we could work around this.

**Comment by tromey** [comment]
I don't really know, but could patchwork store every name a user has gone by?  Or attach the name at the time of sending to a given patch?  I think my situation is something like: I am reading email and see the patch, and want to apply it, and tried using the name.  I suppose I will switch to email addresses out of necessity, but that seems unfortunate.

**Comment by stephenfin** [comment]
> I don't really know, but could patchwork store every name a user has gone by? Or attach the name at the time of sending to a given patch? I think my situation is something like: I am reading email and see the patch, and want to apply it, and tried using the name. I suppose I will switch to email addresses out of necessity, but that seems unfortunate.

It could. Could you report that against [patchwork itself](https://github.com/getpatchwork/patchwork). Not sure how long it would take to get to but it would be a good future work item. Other than that, I'm not sure how else we could resolve this.
