### ISSUE TITLE
Version on pip is outdated, docs are confusing

### ISSUE THREAD

**Issue by gwd** [getpatchwork/git-pw#2]
There has apparently been a major rework of the interface here, which looks good overall.  Unfortunately, the suggestion to use "pip install git-pw" is, at the moment, very bad advice:
- You get the 0.2.0 version interface
- The docs point you to the new interface

Very confusing.  Suggest making a new release and uploading it to pip soon if you can; or at least taking the suggestion to use pip out of the README.

**Comment by stephenfin** [comment]
@gwd I concur. The only reason I haven't done this yet is that this relies on Patchwork v2.0, which isn't released yet. As such, I can't tag `git-pw` v1.0 until that's done.

**Comment by stephenfin** [comment]
I've released 1.0.0 and pushed it to [PyPi](https://pypi.python.org/pypi/git-pw). This should be resolved now. Thanks for the heads up :smile:
