### ISSUE TITLE
Avoid need to escape arguments for "apply" commands

### ISSUE THREAD

**Issue by tromey** [getpatchwork/git-pw#20]
`git pw patch apply` says it runs `git am` under the hood.  It would be nice to be able to pass some options through to `git am`, like `--3way` or `--reject`.  I could not find a way to do that right now.

**Comment by dvhart** [comment]
I was looking for --signoff for "git pw series --signoff XXXX", and was surprised to find it missing. This has been added in the intel drm folks' fork back in 2015: https://github.com/dlespiau/patchwork/commit/f28f1d9e

**Comment by stephenfin** [comment]
> `git pw patch apply` says it runs `git am` under the hood. It would be nice to be able to pass some options through to `git am`, like `--3way` or `--reject`. I could not find a way to do that right now.

This is possible but you need to escape the arguments using ``--``.

    git pw patch apply 123 -- --signoff XXXX

It seems it [should be possible](http://click.pocoo.org/6/advanced/#forwarding-unknown-options) to do this with needing to escape things though. I'll investigate and see if I can resolve this for a 2.0 release.

**Comment by stephenfin** [comment]
> I was looking for --signoff for "git pw series --signoff XXXX", and was surprised to find it missing. This has been added in the intel drm folks' fork back in 2015: dlespiau/patchwork@f28f1d9

That's a completely different tool that just happens to have the same name :see_no_evil: As noted above, this functionality is available here, albeit in slightly modified form.

**Comment by stephenfin** [comment]
@tromey @dvhart Could one of you verify that the changes in https://github.com/getpatchwork/git-pw/pull/21 resolve this for you?

**Comment by dvhart** [comment]
@stephenfin I realized after some investigation that the commit I referenced was completely unrelated - apologies. I'll test your changes now and report back.

**Comment by stephenfin** [comment]
@tromey @dvhart Could one of you verify that the changes in https://github.com/getpatchwork/git-pw/pull/21 resolve this for you?
