### ISSUE TITLE
patch list should provide machine readable formatting string

### ISSUE THREAD

**Issue by andy-shev** [getpatchwork/git-pw#29]
Currently it is hard to format output of the `git pw series list` or `git pw patch list` which makes the output horrible. This needs to have something (preferable `pwclient` compatible) formatting string rules.

**Comment by andy-shev** [comment]
Thanks!
I installed *git-pw* via `pip`, so, if you can tell how to update that, I would switch to newest version with this feature.

**Comment by stephenfin** [comment]
@andy-shev I'm just working through the release process at the moment. Soon as that's done, you'll see it pop up and can install it via `pip install --upgrade git-pw`.

**Comment by andy-shev** [comment]
I have tried new feature.
Notes:
- When simple format is supplied I don't want to see header, just a list of what I asked.
- The output of content takes the same positions independently of how I asked in the command line (the order should be preserved).
- Opposite for the header, it shows always in the order of appearance in the command line, inconsistent with the content. For example `-c ID -c State` shows *ID* followed by *State*, but in content it's *ID* followed by *Name*.
- Also in simple format I would like not to limit *Name*, and print it fully.
- (optional) support comma separated list for `-c` (something like `if len(args.c) == 1: args.c = args.c.split(',')`)

**Comment by stephenfin** [comment]
> *When simple format is supplied I don't want to see header, just a list of what I asked.

I thought about this and came to the conclusion that you had to include a header for things to be useful. Is `git-pw | tail -N +2`. We could look at a `--skip-headers` option later, I guess

> * The output of content takes the same positions independently of how I asked in the command line (the order should be preserved).

Agreed. Unfortunately the code to do this was really ugly and I couldn't think of something nicer in the short amount of time I allocated to this. A future item, for sure.

> * Opposite for the header, it shows always in the order of appearance in the command line, inconsistent with the content. For example `-c ID -c State` shows ID followed by State, but in content it's ID followed by Name.

Could you restate this? I still don't understand.

> * Also in simple (and esp. in csv) format I would like not to limit Name, and print it fully.

Good idea. Another nice change for 1.6.

> * (optional) support comma separated list for `-c` (something like `if len(args.c) == 1: args.c = args.c.split(',')`)

**Comment by andy-shev** [comment]
> > *When simple format is supplied I don't want to see header, just a list of what I asked.
> 
> I thought about this and came to the conclusion that you had to include a header for things to be useful.
> Is `git-pw | tail -N +2`. We could look at a `--skip-headers` option later, I guess

Not exactly as my previous statement, but... I do not see headers anyhow useful when one supplies the list of columns, otherwise I'm fine, `--skip-headers` is a good to have in conjunction with `-f simple`.

> > * The output of content takes the same positions independently of how I asked in the command line (the order should be preserved).
> 
> Agreed. Unfortunately the code to do this was really ugly and I couldn't think of something nicer in the short amount of time I allocated to this. A future item, for sure.

I understand, that's why this is just a set of notes. The current implementation is much better than nothing, thanks for providing it!

> > * Opposite for the header, it shows always in the order of appearance in the command line, inconsistent with the content. For example `-c ID -c State` shows ID followed by State, but in content it's ID followed by Name.
> 
> Could you restate this? I still don't understand.

We have header row in the order of appearance in the command line, for example, `-c ID -c State -c Name` will give in the header `| ID | State |` while actual content would be `| <id> | <name> | <state>` (ordering is not preserved!).

Hope these additions help.

**Comment by andy-shev** [comment]
Just real example

    % git pw patch list --limit 1000 -c ID -c State -c Name

    |     ID | State                                                                    | Name   |
    |--------+--------------------------------------------------------------------------+--------|
    | 997524 | [v0,2/2] Documentation: ARM: sunxi: Add Allwinner SoC T3.                | new    |
