### ISSUE TITLE
Fix handling options on git pw series apply

### ISSUE THREAD

**Issue by ajdlinux** [getpatchwork/git-pw#35]
`git pw series apply -s <series ID>` gives `Error: Invalid value for "SERIES_ID": -s is not a valid integer`.

`git pw series apply <series ID> -s` works as expected, fetching the series and applying the patches with the signoff by passing through the `-s` to `git am`.

This is probably some quirk of the command line parser.

**Comment by stephenfin** [comment]
This should work, no? All unrecognised arguments are passed straight through to `git-am` in recent versions.

**Comment by ajdlinux** [comment]
```
ajd@intelligence:~/code/snowpatch$ git pw series apply -s 81000
Usage: git-pw series apply [OPTIONS] SERIES_ID [ARGS]...
Try "git-pw series apply --help" for help.

Error: Invalid value for "SERIES_ID": -s is not a valid integer
ajd@intelligence:~/code/snowpatch$ git pw --version
git-pw, version 1.5.0
```

**Comment by stephenfin** [comment]
Oh, interesting. What happens if you switch the order (I'm not near a PC to check myself)? Could be a `click` quirk.

**Comment by ajdlinux** [comment]
`git pw series apply 81000 -s` appears to work as expected...

**Comment by stephenfin** [comment]
I've taken a look at this. I don't think it's possible to fix this owing to how the passthrough has been implemented. In short, we swallow all additional arguments *after* the required positional ones to pass to `git-am`. We could do some funkiness where we manually parse the arguments (Is it prefixed with `-` or `--`? Pass it through) but I fear we'd lose a lot of the power of `click` and would break things like the `--help` output. As such, I'm tempted to close this as a `wontfix` or a documentation issue. Thoughts?
