### ISSUE TITLE
Unicode decode issues CSV output

### ISSUE THREAD

**Issue by stephenfin** [getpatchwork/git-pw#49]
As discussed at https://github.com/getpatchwork/git-pw/issues/46#issuecomment-532668539

> ...I'm now seeing a Unicode issue in another case.
> 
> Here is a dump from the DPDK patchwork which works:
> 
> ```
> $ git-pw patch list "bulk" --column ID --column Submitter
> +-------+------------------------------------------+
> |    ID | Submitter                                |
> |-------+------------------------------------------|
> | 59113 | Morten BrÃ¸rup (mb@smartsharesystems.com) |
> +-------+------------------------------------------+
> ```
> 
> However, with the CSV output it throws an exception
> 
> ```
> $ git-pw patch list "bulk" --column ID --column Submitter -f csv
> Traceback (most recent call last):
>   File "/usr/bin/git-pw", line 10, in <module>
>     sys.exit(cli())
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/git_pw/api.py", line 303, in new_func
>     return ctx.invoke(f, *args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/git_pw/patch.py", line 265, in list_cmd
>     utils.echo_via_pager(output, headers, fmt=fmt)
>   File "/usr/lib/python2.7/site-packages/git_pw/utils.py", line 155, in echo_via_pager
>     _echo_via_pager('less', output)
>   File "/usr/lib/python2.7/site-packages/git_pw/utils.py", line 113, in _echo_via_pager
>     c.stdin.write(line.encode(encoding, 'replace'))
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
> "ID","Submitter"
> "59113","Morten Br
> ```

**Comment by john-mcnamara-intel** [comment]
Just to confirm that this now works as expected. Thanks.
