### ISSUE TITLE
use git-pw to download patches, but sometimes can not download or can not fully download

### ISSUE THREAD

**Issue by wanghao75** [getpatchwork/git-pw#65]
1.I have configured my git-pw with 
pw.server="xxx"
pw.token="xxx"
pw.project="xxx"

2.A series of 370 patches has been stored in my patchwork server, but when I use "git-pw series download series_id /home/patches/xx/", 
I have found just 167 patches have been downloaded in the content of /home/patches/xx/xxx.patch

need some help to resolve this, thanks

**Comment by stephenfin** [comment]
This doesn't sound like an issue with `git-pw`. My guess is that if you try to download from the web UI you'll see the same issue. You can try running with the `--debug` flag but there isn't enough here for us to do anything.
